### ISSUE TITLE
PyLint TaskList

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MITunaX#200]
Please update the list below by marking a file done and pick the next one in line.

- [x] metadata.py @cderb ( PR #202 )
- [x] ImportConfigs.py @alexandraBara (PR #204 )
- [x] AnalyzeParseDB.py  @cderb ( PR #203 )
- [x] DataStats.py      @alexandraBara (PR #205 )
- [x] Parsing.py @cderb ( PR #213 )    
- [x] RunPerf.py @alexandraBara (PR #217 )
- [x] Applicability.py @cerb ( PR #228 )
- [x] MachineManagementInterface.py @JehandadKhan  (#224 )
- [x] Worker.py @alexandraBara (PR #225 )
- [x] Evaluator.py @alexandraBara (PR #229 )
- [x] Machine.py @cderb ( PR #235 )
- [x] Builder.py @alexandraBara (PR #230 )
- [x] LoadJob.py @alexandraBara (PR #231 )
- [x] Connection.py @alexandraBara (PR #232 )
- [x] MergePDB.py @cderb ( PR #234 )
- [x] PerfDB.py @cderb ( PR #247 )
- [x] SolverRes.py @alexandraBara (PR #233 )
- [x] BuildDriverCmd.py @alexandraBara (PR #236 ) 
- [x] SQLite2Txt.py @alexandraBara (PR #237)
- [x] ExportConfigs.py @cderb ( PR #239 )
- [x] Metrics.py @JehandadKhan ( #221 )
- [x] QueryDb.py @alexandraBara (PR #241 )
- [x] sql.py @JehandadKhan  ( #222)
- [x] ExportFDB.py @alexandraBara  (PR #238)
- [x] Logger.py @cderb ( PR #240 )
- [x] ParseJobLogs.py @alexandraBara (PR #242 )
- [x] RemDups.py @cderb ( PR #245 )
- [x] Utils.py @alexandraBara (PR #243 )
- [x] CorruptConfigs.py @alexandraBara (PR #249)
- [x] FindDB.py @cderb ( PR #244 )
- [x] RemJobDups.py @cderb ( PR #250 )
- [x] DBCredentials.py @JehandadKhan (PR #253)

ParseLogs.py <-- i @alexandraBara  propose we remove this file, seems useless - ParseJobsLogs can do this if updated
