### ISSUE TITLE
Tuna Scales Perf Db Tuning Tracking Issue

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MITunaX#33]
Tuna Scales [design document](https://amdcloud-my.sharepoint.com/:w:/g/personal/jkhan_amd_com/EWxWeGXXxPxInqnN0Mp_zg8B2RV4Rtn8NdA1AnCaQTPdZw?e=eo2oXn)

## Purpose:
The goal of this issue is to collect and track completion of all the outstanding tasks need to scale up our tuning infrastructure specifically for perf db tuning. Find-Db is a simpler problem which is being tackled in parallel -- some of what is needed here will be used for Find-Db as well. Additionally, precompiled kernels are a separate problem that will likely be an easier technical challenge once these changes have been implemented. 

## Changes:
Changes are outlined per major component. There are some overlap as the lines are not totally clear cut. Some compiler systems are also benchmarking systems. Some changes in one component also requires changes in another at the same time.

### 1. Compiler Server:
This is a new component category. The compiler server (CS)  will compile en masse the kernels being searched for a solver-input-architecture; some CS may have GPUs, others may not. A solver-input-architecture (SIA) is an input configuration for a convolution, with a specific solver targeted, and a specific architecture target. 

- [ ] a. CS must be able compile for multiple architectures. If there exists GPUs on the the CS, the compiled kernels should be for that architecture so as to preserve locality.
- [ ] b. Compile all kernels for a SIA
- [ ] c. Group all kernels for a SIA into a kernel-architecture-solver (KAS) bundle that is a transportable package containing enough metadata to identify its SIA membership
- [ ] d. Maintain system integrity on CPU load, memory usage and disk capacity

### 2. MIOpen:
Changes here require making use of MIOpenTuner and  most likely changes to the internal structure of MIOpen.

- [ ] a. Compile all kernels for a SIA without benchmarking via breaking of the current tuning loop
- [ ] b. Generate metadata for KAS bundling; perhaps tag the name for the architecture
- [ ] c. Load up a KAS that has been shipped to its system and unpack the metadata
- [ ] d. Read metadata and verify the SIA against its GPU archtecture
- [ ] e. Execute benchmarking through MIOpenTuner and modifications to the generic search loop
- [ ] f.  Return information so the SIA entry in the master database (MDB) can be updated

### 3. Benchmark Server:
These benchmarking servers (BS) may also be CS systems, so there needs to be careful provisioning that the systems are not being hobbled by the compilation activities. 

- [ ] a. A docker should be pulled for the current tuning sweep
- [ ] b. rocm-smi needs to set per GPU targeted and per SIA job. This will make sure we don't miss this part of the process if there is a frequency drop
- [ ] c. Execute SIA benchmarking job
- [ ] d. Report back SIA winning configuration

### 4. Master Server:
This system, the master server (MS) coordinates all activities, moves KAS packages from CS to BS systems,  and maintains the forward progress of all the tuning 

- [ ] a. Maintain jobs table with status of SIA needing to be compiled and benchmarked
- [ ] b. Maintain KAS location table 
- [ ] c. Maintain a ready status for all benchmarking server GPU slots
- [ ] d. Move KAS from CS to BS
- [ ] e. Minimize KAS movement by dispatching local compilation jobs on architecture specific BS
- [ ] f. Monitor server load to maintain CS load balance
- [ ] g. Monitor server status for reboot requirements.
- [ ] h. Reset SIA compile and benchmarking jobs on failing servers
- [ ] i. Reset SIA compile jobs on CS node complete failure
- [ ] j. Maintain MDB with updated data based on results from BS SIA runs

### 5. Tuna Updates:
Updates to make Tuna more usable and update-able.

- [ ] Docker-ize a Tuna development environment 
- [ ] Create a pip install package
